yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.Author.as_view(), name='author'),
    path('tech/', views.Technologies.as_view(), name='tech')
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):

        return self.title


class Post(models.Model):
    text = models.TextField(help_text='Введите текст')
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True, null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        verbose_name_plural = 'Посты'
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:settings.POST_STR_SYMBOLS]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField(help_text='Введите текст комментария')
    created = models.DateTimeField(auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'author'],
                                    name='unique_follower_following')
        ]

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст',
            'group': 'Группа',
            'image': 'Картинка'
        }
        help_text = {
            'text': 'Введите текст',
            'group': 'Выберите группу',
            'image': 'Добавьте картинку'
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст комментария'
        }
        help_text = {
            'text': 'Введите комментарий'
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User
from .utils import pages


def index(request):
    '''Принимает запрос, возвращает главную страницу'''
    template = 'posts/index.html'
    posts = Post.objects.select_related('author', 'group')
    page_obj = pages(request, posts)
    context = {
        'page_obj': page_obj
    }
    return render(request, template, context)


def group_posts(request, slug):
    '''Принимает запрос и слаг, возвращает страницу группы'''
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = pages(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    '''Принимает запрос и имя пользователя, возвращает страницу пользователя'''
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = pages(request, posts)
    posts_number = posts.count()
    if request.user.is_authenticated:
        following = Follow.objects.filter(user=request.user,
                                          author=author).exists()
    else:
        following = False
    context = {
        'page_obj': page_obj,
        'author': author,
        'posts_number': posts_number,
        'following': following
    }
    return render(request, template, context)


def post_detail(request, post_id):
    '''Принимает запрос и id поста, возвращает страницу поста'''
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, id=post_id)
    author = post.author
    posts_count = author.posts.filter(author=author).count()
    form = CommentForm(request.POST or None)
    comments = Comment.objects.filter(post=post)
    context = {
        'post': post,
        'posts_number': posts_count,
        'form': form,
        'comments': comments,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    if request.method == 'POST':
        form = PostForm(request.POST or None, files=request.FILES or None)
        if form.is_valid():
            form.instance.author = request.user
            form.save()
            return redirect('posts:profile', username=request.user)
    form = PostForm(request.POST or None, files=request.FILES or None)
    context = {
        'form': form,
        'title': 'Новый пост',
    }
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)
    if request.user == post.author:
        if request.method == 'POST':
            form = PostForm(request.POST or None,
                            files=request.FILES or None,
                            instance=post)
            if form.is_valid():
                form.save()
                return redirect('posts:post_detail', post_id)
        form = PostForm(
            request.POST or None,
            files=request.FILES or None,
            instance=post)
        context = {
            'title': 'Редактировать запись',
            'form': form,
            'is_edit': True,
            'post': post
        }
        return render(request, template, context)
    else:
        return redirect('posts:post_detail', post_id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    posts = Post.objects.filter(
        author__following__user=request.user,
    ).select_related('author', 'group')
    page_obj = pages(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    user = get_object_or_404(User, username=request.user)
    author = get_object_or_404(User, username=username)
    if user == author:
        return redirect('posts:profile', username=username)
    Follow.objects.get_or_create(author=author, user=request.user)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
<!DOCTYPE html> 
<html lang="ru">
{% extends 'base.html' %}
  <head>    
    {% block title %}
        <title> {{title}} </title>
    {% endblock %}
  </head>
  <body>	   
    <header>
    </header>
    <main>
      {% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактировать запись
                {% else %}
                  Новый пост
                {% endif %}             
              </div>
              <div class="card-body">
                {% load user_filters %}
                {% if form.errors %}
                  {% for field in forms %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div> 
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endif %}
                {% if is_edit %}
                  <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post_id=post.id %}">
                {% else %}
                  <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
                {% endif %}>
                {% csrf_token %}
                {% for field in form %}
                  <div class="form-group row my-3 p-3">
                    <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                        {% if field.field.required %}                  
                          <span class="required text-danger" >*</span>
                        {% endif %}                 
                    </label>
                    {{ field|addclass:'form-control' }}
                      {% if field.help_text %}
                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                          {{ field.help_text|safe }}
                        </small>
                      {% endif %}
                  </div>
                {% endfor %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endblock %}
    </main>
    <footer class="border-top text-center py-3">   
    </footer>
  </body>
</html>

yatube/templates/posts/follow.html
<!DOCTYPE html>
<html lang="ru">
{% extends 'base.html' %}
  <head>
    {% block title %}
      <title>Подписки</title>
    {% endblock %}
  </head>
  <body>
    <header>
    </header>
    <main> 
      {% block content %}
        <div class="container py-5">  
          <h1>Мои подписки</h1>
          {% include 'includes/switcher.html' %}
          {% for post in page_obj %}
            {% include 'includes/post_list.html' %}
          {% endfor %}
          {% include 'includes/paginator.html' %}
        </div>  
      {% endblock %}  
    </main>       
    <footer class="border-top text-center py-3">  
    </footer>
  </body>
</html>

yatube/templates/posts/group_list.html
<!DOCTYPE html>
<html lang="ru">
{% extends 'base.html' %}
  <head>
    {% block title %}
      <title>Записи группы {{ group }}</title>
    {% endblock %}
  </head>
  <body>
    <header>     
    </header>
    <main>
      {% block content %}
        <div class="container py-5">     
          <h1>{{ group }}</h1>
          <p> {{ group.description }} </p>
          {% for post in page_obj %}
            {% include 'includes/post_list.html' %}
          {% endfor %}
          {% include 'includes/paginator.html' %}
        </div>
      {% endblock %}  
    </main>
    <footer class="page-footer font-small blue border-top">
    </footer>
  </body>
</html>

yatube/templates/posts/index.html
<!DOCTYPE html>
<html lang="ru">
{% extends 'base.html' %}
  <head>
    {% block title %}
      <title>Последние обновления на сайте</title>
    {% endblock %}
  </head>
  <body>
    <header>
    </header>
    <main> 
      {% block content %}
        <div class="container py-5">  
          <h1>Последние обновления на сайте</h1>
          {% include 'includes/switcher.html' %}
          {% load cache %}
          {% cache 20 index_page %}
          {% for post in page_obj %}
            {% include 'includes/post_list.html' %}
          {% endfor %}
          {% include 'includes/paginator.html' %}
          {% endcache %}
        </div>  
      {% endblock %}  
    </main>       
    <footer class="border-top text-center py-3">  
    </footer>
  </body>
</html>

yatube/templates/posts/post_detail.html
<!DOCTYPE html>
<html lang="ru">
{% extends 'base.html' %}
{% load thumbnail %}
  <head>
    {% block title %}
      <title>Пост: {{ post.text|truncatechars:30 }}</title>
    {% endblock %}
  </head>
  <body>
    <header>     
    </header>
    <main>
      {% block content %}
        <div class="row">
          <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
              {% if post.group %}   
                <li class="list-group-item">
                  Группа: {{ post.group.title }}
                  <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
                </li>
              {% endif %}
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                Всего постов автора:  <span >{{ posts_number }}</span>
              </li>
              <li class="list-group-item">
                <a href="{% url 'posts:profile' post.author %}">
                  все посты пользователя
                </a>
              </li>
            </ul>
          </aside>
          <article class="col-12 col-md-9">
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>
              {{ post.text }}
            </p>
            {% if user == post.author %}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
              Редактировать пост
            </a>
            {% endif %}
          </article>
          {% include 'includes/add_comment.html' %}
        {% endblock %}
      </div> 
    </main>
    <footer class="border-top text-center py-3">
    </footer>
  </body>
</html> 

yatube/templates/posts/profile.html
<!DOCTYPE html>
<html lang="ru">
{% extends 'base.html' %}
  <head>  
    {% block title %}
      <title>Профайл пользователя {{ author.get_full_name }} </title>
    {% endblock %}
  </head>
  <body>       
    <header>     
    </header>
    <main>
      {% block content %}
        <div class="container py-5">        
          <h1>Все посты пользователя {{ author.get_full_name }} </h1>
          <h3>Всего постов: {{ posts_number }} </h3>
          {% if author.id != request.user.id %}
            {% if following %}
            <a
              class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
              Отписаться
            </a>
            {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
            {% endif %}
          {% endif %}
          {% for post in page_obj %}
            {% include 'includes/user_posts.html' %}
          {% endfor %}
          {% include 'includes/paginator.html' %}
        </div>
      {% endblock %}
    </main>
    <footer class="border-top text-center py-3">   
    </footer>
  </body>
</html>